### ISSUE TITLE
Coordinate with https://github.com/ncalexan/rust-android-gradle

### ISSUE THREAD

**Issue by ncalexan** [nishtahir/rust-android-gradle#2]
Hi @nishtahir!  Thanks so much for your work on this plugin.

I work for Mozilla and we're using your plugin to build some Rust-y Android components, starting with the [Mentat Android SDK](https://github.com/mozilla/mentat/tree/master/sdks/android/Mentat).  I've picked up your work and have some features and changes that I've pushed to https://github.com/ncalexan/rust-android-gradle and published under `org.mozilla.rust-android-gradle.rust-android`.  (I definitely didn't want to conflict with your work!)

I'd like to collaborate so that there's only one version of this plugin; the only reason I didn't was that I had lots of things to address and wanted to get something working on a tight schedule.  I'd prefer if this didn't live in the `org.mozilla` namespace, since it's really not Mozilla-specific, so if you're interested in developing this further, please let me know.  If not, just close out this ticket and I'll continue developing my own fork.

Once again, thanks for setting down a template for how this can work!

**Comment by nishtahir** [comment]
Thanks for reaching out. 

I'm super interested in continuing to work on this. I would love to merge your changes in as they contribute excellent improvements to the project. I'd be happy to publish this under my own namespace.
